### ISSUE TITLE
<em> 태그가 반영되지 않음

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#35]
게시판에서 기울임체 사용시 입력되는 `<em>` 태그가 강제 지정되어 있어 기울임꼴 지정을 해도 똑같이 보입니다.
이는 `/assets/common/css/normalize.css` 에서
```css
em{font-style: normal}
```
으로 초기화하고 따로 지정해주지 않아 발생하는 문제입니다.
