### ISSUE TITLE
memebr settings.css 불필요 코드 및 오류 제거

### ISSUE THREAD

**Issue by seungmanchoi** [xpressengine/xpressengine#380]
이미지 경로 및 selector 문제로 확인됩니다.

```css
.setting-card.login-connect .xe-btn xe-btn-text {
  margin: 0 12px 0 0;
  color: #2c8beb;
  font-size: 15px;
}

.setting-group .text-red + .xe-btn xe-btn-text {
  margin-left: 10px;
}

.setting-card .xe-input-group .xe-btn xe-btn-text {
  height: auto;
  line-height: inherit;
  padding: 0;
}

.snb {
  display: block;
  position: fixed;
  left: -240px;
  top: 0;
  bottom: 0;
  width: 240px;
  height: auto;
  padding-top: 60px;
  z-index: 1100;
  box-sizing: border-box;
  overflow: hidden;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  background: url(bg_set_snb.gif) 0 0 repeat-y;
}

.setting-wrap .snb-list:after {
  position: absolute;
  top: -9px;
  left: 20px;
  width: 16px;
  height: 9px;
  background: url(ico_menu_arrow.png) 0 0 no-repeat;
  background-size: 16px 9px;
  content: "";
}
```
